name: NotesApplication
options:
  bundleIdPrefix: com.notesapplication
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "15.0.1"
targets:
  NotesApplicationApp:
    type: application
    platform: iOS
    sources: [NotesApplication]
    info:
      path: NotesApplication/Info.plist
  NotesApplicationTests:
    type: bundle.unit-test
    platform: iOS
    sources: [NotesApplicationTests]
    dependencies:
      - target: NotesApplicationApp
    info:
      path: NotesApplicationTests/Info.plist
  NotesApplicationUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [NotesApplicationUITests]
    dependencies:
      - target: NotesApplicationApp
    info:
      path: NotesApplicationUITests/Info.plist
