name: NotesApplication
options:
  bundleIdPrefix: com.notesapplication
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "14.3.1"
targets:
  NotesApplicationApp:
    type: application
    platform: iOS
    sources: [NotesApplication]
    info:
      path: NotesApplication/Info.plist
  NotesApplicationTests:
    type: bundle.unit-test
    platform: iOS
    sources: [NotesApplicationTests]
    dependencies:
      - target: NotesApplicationApp
    info:
      path: NotesApplicationTests/Info.plist
