name: NotesApplicationJobs

on:
  push:
    branches:
      - main

jobs:
  test:
    name: NotesApplicationTests
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: 14.2
      - name: Install Mint
        run: brew install mint
      - name: Generate Xcode project
        run: mint bootstrap && mint run xcodegen
      - name: Install Bundler
        run: gem install bundler:2.2.16
      - name: Bundle Install
        run: bundle install
      - name: CocoaPods
        run: bundle exec pod install
      - name: Build and test
        run: xcodebuild test -workspace NotesApplication.xcworkspace -scheme NotesApplicationApp -destination "platform=iOS Simulator,OS=16.2,name=iPhone 8"
